const carouselNewItems = [
  {
    deadline: 'January, 10, 2022',
    imgUrl: '/home1',
    author: './images/author/author-1.jpg',
    static: './images/items/static-1.jpg',
    titleUrl: '/#',
    title: 'Pinky Ocen',
    price: { label: '0.08ETH', value: '1/20' },
    likes: 50,
  },
  {
    imgUrl: '/#',
    author: './images/author/author-10.jpg',
    static: './images/items/static-2.jpg',
    titleUrl: '/#',
    title: 'Deep Sea Phantasy',
    price: { label: '0.06ETH', value: '1/22' },
    likes: 80,
  },
  {
    deadline: 'February, 10, 2022',
    imgUrl: '/#',
    author: './images/author/author-11.jpg',
    static: './images/items/static-3.jpg',
    titleUrl: '/#',
    title: 'Rainbow Style',
    price: { label: '0.05ETH', value: '1/11' },
    likes: 97,
  },
  {
    imgUrl: '/#',
    author: './images/author/author-12.jpg',
    static: './images/items/static-4.jpg',
    titleUrl: '/#',
    title: 'Two Tigers',
    price: { label: '0.02ETH', value: '1/15' },
    likes: 73,
  },
  {
    imgUrl: '/#',
    author: './images/author/author-9.jpg',
    static: './images/items/anim-4.webp',
    titleUrl: '/#',
    title: 'The Truth',
    price: { label: '0.06ETH', value: '1/20' },
    likes: 26,
  },
  {
    imgUrl: '/#',
    author: './images/author/author-2.jpg',
    static: './images/items/anim-2.webp',
    titleUrl: '/#',
    title: 'Running Puppets',
    price: { label: '0.03ETH', value: '1/24' },
    likes: 45,
  },
];

export default carouselNewItems;
